 import java.util.Random;

/**
 * Enemy2D.java
 * 
 * This concrete class inherits from NonPlayerCharacter. 
 * 
 * @author Jaylon Kiper
 * @version 1.0
 * Programming Project 3
 * SP19
 */
public class Enemy2D extends NonPlayerCharacter {
	
	private int xPos;//represents the object’s location on the x-axis in two-dimensional space
	private int yPos;//represents the object’s location on the y-axis in two-dimensional space
	private int numberOfTorpedoes;//represents how many torpedoes the object can shoot

	/**
	 *  Empty-argument constructor that should set 
	 *  default values for all of the object’s data, 
	 *  except uniqueID, which is randomly generated 
	 *  by GameUtilities. (inherited functionality) 
	 */
	public Enemy2D() {
		xPos = 0;
		yPos = 0;
		numberOfTorpedoes = 0;
	}//end empty-argument constructor
	
	/**
	 *  Preferred constructor that should set accept x and y coordinates 
	 *  and number of torpedoes as parameters except uniqueID, 
	 *  which is randomly generated by GameUtilities. (inherited functionality) 
	 */
	public Enemy2D(int x, int y, int numberOfTorpedoes) {
		this.setXPos(x);
		this.setYPos(y);
		this.setNumberOfTorpedoes(numberOfTorpedoes);
	}//end preferred constructor
	
	/**
	 * move(int x, int y), which updates the 
	 * object’s position to the new coordinates. 
	 */
	public void move(int x, int y) {
		xPos = x;
		yPos = y;
	}//end move

	/**
	 * fire(), which “fires” a torpedo. In this method, 
	 * if the object still has torpedoes, 
	 * the numberTorpedoes instance field needs 
	 * to be reduced by one and it should return true. 
	 * Otherwise, it should return false. 
	 * @return
	 */
	public boolean fire() {
		if(numberOfTorpedoes > 0) {
			numberOfTorpedoes--;
			return true;
		}
		else
			return false;
			
	}//end fire

	/**Getter for xPos
	 * @return xPos
	 */
	public int getXPos() {
		return xPos;
	}//end getXPos

	/**
	 * Setter for xPos
	 * @param xPos
	 */
	public void setXPos(int x) {
		this.xPos = x;
	}//end setXpos

	/**Getter for yPos
	 * @return yPos
	 */
	public int getYPos() {
		return yPos;
	}//end getYPos

	/**
	 * Setter for yPos
	 * @param yPos
	 */
	public void setYPos(int y) {
		this.yPos = y;
	}//end setYPos
	
	/**
	 * Getter for the numberOfTorpedoes
	 * @return numberTorpedoes
	 */
	public int getNumberOfTorpedoes() {
		return numberOfTorpedoes;
	}//end getNumberOfTorpedoes

	/**
	 * Setter for the numberOfTorpedoes
	 * @param numberOfTorpedoes
	 */
	public void setNumberOfTorpedoes(int numberOfTorpedoes) {
		this.numberOfTorpedoes = numberOfTorpedoes;
	}//end setNumberTorpedoes

	@Override
	public String introduce() {
		return "I,DIO,will end your existence immediately!";
	}//end introduce

	@Override
	public String exclaim() {
		String quotes[] = new String[5];
		quotes[0]="Ahhh! I'm taking damage.";
		quotes[1]="IMMOPOSIBLE! I am the mighty DIO!";
		quotes[2]="What is this strength?!";
		quotes[3]="Don't think you got the best of me.";
		quotes[4]="Your efforts are USELESS!";
		Random generator = new Random();
		int exclaimation = generator.nextInt(5);
		return quotes[exclaimation];
	}//end exclaim

	public String reportStructure() {
		String declaration = "--------------------------------------\n";
		declaration+= 		 "|              Enemy2D	             |\n";
		declaration+= 		 "--------------------------------------\n";
		declaration+=		 "|IS A SUBCLASS                       |\n";
		declaration+=        "--------------------------------------\n";
		declaration+=		 "|"+getUniqueID()+"                  |\n";
		declaration+=		 "|"+getIntelligenceType()+"                            |\n";
		declaration+=		 "|"+getPersonalityType()+"                                |\n";
		declaration+=		 "|"+getActive()+"                                |\n";
		declaration+=		 "|"+getXPos()+"                                   |\n";
		declaration+=		 "|"+getYPos()+"                                   |\n";
		declaration+=		 "|"+getNumberOfTorpedoes()+"                                   |\n";
		declaration+=		 "|"+introduce()+" |\n";
		declaration+=		 "|"+exclaim()+"             |\n";
		declaration+=        "--------------------------------------\n";
		return declaration;
	}//end reportStructure
}//end class
