/**
 * HumanPlayer.java
 * 
 * This concrete class models a human player of a video game.
 * 
 * @author Jaylon Kiper
 * @version 1.0
 * Programming Project 3
 * SP19
 */
public class HumanPlayer implements Reportable{
	
	protected String uniqueID;//generated by the generateID() method in the GameUtilities class
	private String name;//a String representation of the character that could be displayed on a leaderboard, printed to the screen, etc
	private SkillLevelType skillLevel;//could be used by an AI engine to adjust the difficult of the game
	
	/**
	 * Empty-argument constructor that should set 
	 * default values for all of the object’s data, 
	 * except uniqueID, which is randomly generated by GameUtilities. 
	 */
	public HumanPlayer() {
		uniqueID = GameUtilities.generateID();
		name = "Jotaro";
		skillLevel = SkillLevelType.EXPERT;
	}//end empty-argument constructor
	
	/**
	 * Preferred constructor that should set accept name 
	 * and skillLevel as parameters except uniqueID, 
	 * which is randomly generated by GameUtilities. 
	 * @param name
	 * @param skillLevel
	 */
	public HumanPlayer(String n, SkillLevelType s) {
		uniqueID = GameUtilities.generateID();
		this.setName(n);
		this.setSkillLevelType(s);
	}//end preferred constructor
	
	/**
	 * Getter for the uniqueID
	 * @return uniqueID
	 */
	public String getUniqueID() {
		return uniqueID;
	}//end getUniqueID
	
	/**
	 * Getter for the name
	 * @return name
	 */
	public String getName() {
		return name;
	}//end getName

	/**
	 * Setter for the name
	 * @param name
	 */
	public void setName(String n) {
		this.name = n;
	}//end setName

	/**Getter for skillLevel
	 * @return skillLevel
	 */
	public SkillLevelType getSkillLevelType() {
		return skillLevel;
	}//end getSkillLevelType

	/**
	 * Setter for skillLevel
	 * @param skillLevel
	 */
	public void setSkillLevelType(SkillLevelType s) {
		this.skillLevel = s;
	}//end SkillLevelType

	@Override
	public String reportStructure() {
		String declaration = "--------------------------------------\n";
		declaration+= 		 "|            HumanPlayer             |\n";
		declaration+= 		 "--------------------------------------\n";
		declaration+=		 "|NOT A SUBCLASS                      |\n";
		declaration+=        "--------------------------------------\n";
		declaration+=		 "|"+getUniqueID()+"                  |\n";
		declaration+=		 "|"+getName()+"                              |\n";
		declaration+=		 "|"+getSkillLevelType()+"                              |\n";
		declaration+=        "--------------------------------------\n";
		return declaration;
	}//end reportStructure

}//end class
